### ISSUE TITLE
Problem i donet

### ISSUE THREAD

**Issue by Noiden** [fulhax/mpdbot#1]
Donet funkar inte.

**Comment by c0r73x** [comment]
Låter helt klart som ett användar fel, har du testat att starta om donet?

**Comment by Noiden** [comment]
Njaa, hittade inte kommandot för att starta om donet, donet är svårt att hitta också tycker jag. Vet du hur man fångar in donet för att sen starta om?

**Comment by c0r73x** [comment]
Humm har varit med om liknande problem. Tror att det lättaste är att testa att avinstallera donet sen installera det igen. Alternativt testa en äldre version t.ex. donet 3.1.

**Comment by rendom** [comment]
@Noiden kan krävas benbit och trumma för att starta donet, prova det och återkom tack!

**Comment by Noiden** [comment]
Aah, jag körde ./benbit --include trumma --remove donet && ./trumma --include benbit --install donet && service restart donet och nu funkar det fina nåjden!
